# Generated by Django 4.1.5 on 2023-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-03-15'),
            preserve_default=False,
        ),
    ]
